name: iOS CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Xcode version
        run: sudo xcode-select -switch /Applications/Xcode_14.2.app/Contents/Developer

      - name: Install Simulator
        run: |
          sudo xcrun simctl list runtimes
          sudo xcrun simctl create 'iPhone 11' com.apple.CoreSimulator.SimDeviceType.iPhone-11 com.apple.CoreSimulator.SimRuntime.iOS-15-2

      - name: Build and Test
        run: xcodebuild build-for-testing -scheme TrialGA -project ./TrialGA.xcodeproj -destination "platform=iOS Simulator,name=iPhone 11"
