name: Build Swift Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_14.2.app/Contents/Developer'
    - name: Build Project
      run: xcodebuild build -project TrialGA.xcodeproj -scheme TrialGA
